[general]
name = "deformable-detr"
version = 1
license = "Apache-2.0"
backends = ["cuda"]
upstream = "https://github.com/S-aiueo32/torch-ms-deform-attn"

[general.hub]
repo-id = "kernels-community/deformable-detr"

[torch]
src = ["torch-ext/torch_binding.cpp", "csrc/dispatcher.h"]
include = ["csrc"]

[kernel.msda]
backend = "cuda"
depends = ["torch"]
include = ["csrc"]
src = [
    "csrc/cuda/ms_deform_attn_cuda.cu",
    "csrc/cuda/ms_deform_attn_cuda.h",
    "csrc/cuda/ms_deform_im2col_cuda.cuh",
    "csrc/cuda/index_utils.h",
]
